import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import Link from "next/link";

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>Welcome to this reproduction program!</h1>

        <p className={styles.description}>
          This repo has two api routes. One of them is slow, which is expected
          even running locally, but it is extremely slow when running in
          production.
        </p>
        <p>The two routes are:</p>
        <p>
          <code className={styles.code}>
            <Link href="/api/apple">
              <a>/api/apple</a>
            </Link>
          </code>{" "}
          - this proves that the image can be loaded and served very fast.
        </p>
        <p>
          <code className={styles.code}>
            <Link href="/api/apple-sqip">
              <a>/api/apple-sqip</a>
            </Link>
          </code>{" "}
          - this shows the difference in speed when running locally vs. running
          in production. Locally it takes around 6 seconds, but on production
          takes much longer, to the point of the entire api call timing out.
        </p>
        <p>
          <code className={styles.code}>
            <Link href="/api/apple-sqip?primatives=100">
              <a>/api/apple-sqip?primatives=100</a>
            </Link>
          </code>{" "}
          - a quicker example - takes around 1 second running locally, but around 45 seconds on production.
        </p>

        <br />
        <br />

        <div className={styles.grid}>
          <a
            href="https://github.com/williamforty/sqip-slow-reproduction"
            className={styles.card}
          >
            <h2>View the GitHub Repository &rarr;</h2>
            <p>Take a look at the source code for this NextJs application</p>
          </a>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
};

export default Home;
